### ISSUE TITLE
Subscribing feature is hidden

### ISSUE THREAD

**Issue by michaelfdeberry** [DittoToday/Feedback#31]
Hi! Great work so far. Really loving the fact that this exists.

I was just clicking around the interface and saw that there is a subscription feature hidden behind the hamburger menu all the way to the right.

IMHO that subscription feature will be the most powerful way to make use of Ditto - especially when it begins to fill with lots of content. I recommend making it more apparent that there is a subscription feature that is part of Ditto. Perhaps not hiding it behind the hamburger?

Hope that's a helpful bit of feedback. I will commit to providing more as I use the site more.

For reference, my favorite aggregator is usepanda.com. I think their product is not as focused as Ditto, but they manage to pull off a pretty good UI even considering all of the things they're trying to surface.

Props to you and your team (or just you if it's a one-person thing)!

Best

**Comment by qaid** [comment]
![hidden-subscriptions-behind-hamburger](https://cloud.githubusercontent.com/assets/2238082/11040718/0552621a-870e-11e5-91d7-ebcd346d04c5.png)

**Comment by michaelfdeberry** [comment]
This has come up a lot actually. I will definitely have to come up with improvements here. 

The current implementation does favors larger screens, because if there is enough room the communities menu will initially be open until the user closes it. 

Something that I am considering is to get rid of the margins and always have the communities menu open.

**Comment by qaid** [comment]
Nice idea.

Another idea you could consider: the horizontal nav items are clearly the place where I can perform most actions. Since subscribing to a community is one of the most valuable actions, why not toss a link up there called "your communities" or somethin that just triggers that same off-canvas action. That way you don't even have to bother the hamburger since it works in some contexts. For users with large viewports, hide the horizontal nav item since they will already be seeing the sidebar.

_BTW - is this built on top of Telescope?_

**Comment by michaelfdeberry** [comment]
That's a great idea, and it's essentially just moving the button and replacing the icon with text. I will give that a try.

Thank you.

**Comment by qaid** [comment]
Custom?! Nice. Well done, Sir!

I'm excited to use Ditto and help it to be a viable alternative.

👊🏿
